image_root: '/temp/vl-dataset/common-images/flickr30k/' #flickr30k-images/
ann_root: '/temp/vl-dataset/json_downstream/retrieval/'
dataset: 'flickr'

# set pretrained as a file path or an url
pretrained: '~/projects/prune/BLIP/output/Pretrain/checkpoint_14.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 16 # 32
batch_size_test: 32 # 64
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 10
# init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 128
negative_all_rank: False

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

