train_file: [
  '/temp/vl-dataset/json_pretrain/coco.json',
  '/temp/vl-dataset/json_pretrain/vg.json',
  # '/temp/vl-dataset/json_pretrain/cc12m.json',
  '/temp/vl-dataset/json_pretrain/cc3m_train.json',
  '/temp/vl-dataset/json_pretrain/cc3m_val.json',
  '/temp/vl-dataset/json_pretrain/sbu.json'
  ]
# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }
bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 40 #58
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 20, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 10, cooldown_epochs: 0}

# (begin layer id, num of used layers, keep ratio)
img_prune: {
  begin_layer: [2, 4, 10],
  num_act_layers: [2, 6, 2],
  keep_ratio: [0.90, 0.65, 0.40]
  }